#!/usr/bin/env python3
# gen-sources.py — regenerate js/sources.js from the app's actual source files.
#
# js/sources.js holds each source file's text as a string map on window.__SOURCES.
# "Export site" (js/settings.js) reads that map to inline the whole app into a
# single self-contained index.html — needed because under file:// a fetch of a
# sibling file is blocked, so the app cannot read its own source off disk.
#
# RUN THIS whenever any source file (index.html, styles.css, or any js/*.js
# except sources.js) changes, or Export site will ship stale code:
#
#     python3 tools/gen-sources.py
#
# It writes js/sources.js. sources.js is intentionally NOT included in the map
# (Export re-emits the live window.__SOURCES for it instead).

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    sources = {}

    # Top-level files.
    for name in ("index.html", "styles.css"):
        with open(os.path.join(ROOT, name), "r", encoding="utf-8") as fh:
            sources[name] = fh.read()

    # Every js/*.js in filename order, except this generator's own output and the
    # icon-library catalog (iconlib.js is a ~1MB design-time browse catalog; icons
    # the user actually picks are copied into config, so exports stay small).
    js_dir = os.path.join(ROOT, "js")
    for fname in sorted(os.listdir(js_dir)):
        if not fname.endswith(".js") or fname in ("sources.js", "iconlib.js"):
            continue
        with open(os.path.join(js_dir, fname), "r", encoding="utf-8") as fh:
            sources["js/" + fname] = fh.read()

    header = (
        "// sources.js — GENERATED by tools/gen-sources.py. DO NOT EDIT BY HAND.\n"
        "//\n"
        "// A map of every source file's text, used by \"Export site\" to inline the\n"
        "// whole app into one self-contained index.html (a fetch of a sibling file is\n"
        "// blocked under file://, so the app reads its source from here instead).\n"
        "//\n"
        "// REGENERATE whenever any source changes, or Export site ships stale code:\n"
        "//     python3 tools/gen-sources.py\n"
        "\n"
        "window.__SOURCES = "
    )

    body = json.dumps(sources, ensure_ascii=False, indent=0)
    out = header + body + ";\n"

    with open(os.path.join(js_dir, "sources.js"), "w", encoding="utf-8") as fh:
        fh.write(out)

    print("Wrote js/sources.js with %d files: %s" % (len(sources), ", ".join(sorted(sources))))


if __name__ == "__main__":
    main()
